name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build Win
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Upload *nix Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: esl-services-backend
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release
        if-no-files-found: warn
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: esl-services-backend.exe
        # A file, directory or wildcard pattern that describes what to upload
        path: target/x86_64-pc-windows-gnu/release
        if-no-files-found: warn
