name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          target: x86_64-pc-windows-gnu

    - name: Build
      uses: actions-rs/cargo@v1
      with: 
        command: build 
        args: --verbose
        
    - name: Build Win
      uses: actions-rs/cargo@v1
      with: 
        command: build 
        args: --release --target x86_64-pc-windows-gnu

    - name: Run tests
      uses: actions-rs/cargo@v1
      with: 
        command: test 
        args: --verbose
    - name: Upload *nix Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: esl-services-backend
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release
        if-no-files-found: warn
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: esl-services-backend.exe
        # A file, directory or wildcard pattern that describes what to upload
        path: target/x86_64-pc-windows-gnu/release
        if-no-files-found: warn
